### ISSUE TITLE
Validation Failed: 1: scrollId is missing

### ISSUE THREAD

**Issue by kerven88** [YouCD/esDump#1]
/opt/esDump --export \
>     --endpoint http://127.0.0.1:9200/forseti-r-20211118 \
>     --size 200 \
>     --query '{"range": {"activity.S_T_VD_EVENTOCCURDATE.raw": {"gte": "2021-11-18 00:00:00", "lt": "2021-11-19 00:00:00"}}}'

报错如下：
2021/11/19 10:09:27 Error response: [400 Bad Request] {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"},"status":400}

 麻烦帮忙看下是什么原因？

**Comment by YouCD** [comment]
已经修复了，原来是不支持复杂的查询, 可以下载 6.0 相应的版本 [地址](https://github.com/YouCD/esDump/releases/tag/v6.8.23)
